// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKzbY962RSbei8U_chc1SV0nmXIvdG7E',
    appId: '1:428408602290:web:b2db40ff2aaa307e1ad3ab',
    messagingSenderId: '428408602290',
    projectId: 'mybasicwebsite-91259',
    authDomain: 'mybasicwebsite-91259.firebaseapp.com',
    storageBucket: 'mybasicwebsite-91259.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdwQcnu1ILIJWsfMtkN4aqEk98ynuEH1o',
    appId: '1:428408602290:android:efe7e50ca26d47ee1ad3ab',
    messagingSenderId: '428408602290',
    projectId: 'mybasicwebsite-91259',
    storageBucket: 'mybasicwebsite-91259.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA38FpAu7tDPlzvdeOemKj3Dddv0AWEB-c',
    appId: '1:428408602290:ios:98dc6a26b39ac2001ad3ab',
    messagingSenderId: '428408602290',
    projectId: 'mybasicwebsite-91259',
    storageBucket: 'mybasicwebsite-91259.appspot.com',
    iosBundleId: 'com.example.theBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA38FpAu7tDPlzvdeOemKj3Dddv0AWEB-c',
    appId: '1:428408602290:ios:98dc6a26b39ac2001ad3ab',
    messagingSenderId: '428408602290',
    projectId: 'mybasicwebsite-91259',
    storageBucket: 'mybasicwebsite-91259.appspot.com',
    iosBundleId: 'com.example.theBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKzbY962RSbei8U_chc1SV0nmXIvdG7E',
    appId: '1:428408602290:web:3542fc66ba271bc51ad3ab',
    messagingSenderId: '428408602290',
    projectId: 'mybasicwebsite-91259',
    authDomain: 'mybasicwebsite-91259.firebaseapp.com',
    storageBucket: 'mybasicwebsite-91259.appspot.com',
  );
}
